### ISSUE TITLE
誤植：「3.2.2.1. 補足：交差エントロピーについて」

### ISSUE THREAD

**Issue by yukkyo** [japan-medical-ai/medical-ai-course-materials#82]
[該当箇所](https://japan-medical-ai.github.io/medical-ai-course-materials/notebooks/Introduction_to_Neural_Network.html#%E8%A3%9C%E8%B6%B3%EF%BC%9A%E4%BA%A4%E5%B7%AE%E3%82%A8%E3%83%B3%E3%83%88%E3%83%AD%E3%83%94%E3%83%BC%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)にあります

<a href="https://www.codecogs.com/eqnedit.php?latex=\int_{x,&space;y}&space;\hat{p}(y|x)&space;\log&space;\frac{q(y|x)}{\hat{p}(y|x)}&space;dx&space;dy" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\int_{x,&space;y}&space;\hat{p}(y|x)&space;\log&space;\frac{q(y|x)}{\hat{p}(y|x)}&space;dx&space;dy" title="\int_{x, y} \hat{p}(y|x) \log \frac{q(y|x)}{\hat{p}(y|x)} dx dy" /></a>

は交差エントロピーではなく KL divergence に -1 をかけたものに見えます。

<a href="https://www.codecogs.com/eqnedit.php?latex=-&space;\int_{x,&space;y}&space;\hat{p}(y|x)&space;\log&space;q(y|x)&space;dx&space;dy" target="_blank"><img src="https://latex.codecogs.com/gif.latex?-&space;\int_{x,&space;y}&space;\hat{p}(y|x)&space;\log&space;q(y|x)&space;dx&space;dy" title="- \int_{x, y} \hat{p}(y|x) \log q(y|x) dx dy" /></a>

だったりしませんでしょうか？

**Comment by hillbig** [comment]
ありがとうございます。おっしゃる通りです。ここは説明として、KL(p||q)のqについての最小化として、交差エントロピーがでてくるのですが、KL（しかもそれの負）を紹介してしまっていました。修正いたします

**Comment by yukkyo** [comment]
ありがとうございます
恐縮ですがご対応よろしくお願いいたします 🙇

**Comment by mitmul** [comment]
Solved by #83
