### ISSUE TITLE
誤植「5.5.1. Convolutionレイヤ」

### ISSUE THREAD

**Issue by yukkyo** [japan-medical-ai/medical-ai-course-materials#85]
[該当箇所](https://japan-medical-ai.github.io/medical-ai-course-materials/notebooks/Image_Segmentation.html#Convolution%E3%83%AC%E3%82%A4%E3%83%A4)にあります

<a href="https://www.codecogs.com/eqnedit.php?latex=({\rm&space;input\_size}&space;&plus;&space;{\rm&space;pad}&space;\times&space;2)&space;/&space;{\rm&space;stride}&space;&plus;&space;1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?({\rm&space;input\_size}&space;&plus;&space;{\rm&space;pad}&space;\times&space;2)&space;/&space;{\rm&space;stride}&space;&plus;&space;1" title="({\rm input\_size} + {\rm pad} \times 2) / {\rm stride} + 1" /></a>

は正しくは

<a href="https://www.codecogs.com/eqnedit.php?latex=({\rm&space;input\_size}&space;&plus;&space;{\rm&space;pad}&space;\times&space;2&space;-&space;{\rm&space;ksize})&space;/&space;{\rm&space;stride}&space;&plus;&space;1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?({\rm&space;input\_size}&space;&plus;&space;{\rm&space;pad}&space;\times&space;2&space;-&space;{\rm&space;ksize})&space;/&space;{\rm&space;stride}&space;&plus;&space;1" title="({\rm input\_size} + {\rm pad} \times 2 - {\rm ksize}) / {\rm stride} + 1" /></a>

だと思われます。
ご確認お願いします。

**Comment by suga93** [comment]
該当箇所について，修正・反映致しました．
ご指摘いただきありがとうございました．
