### ISSUE TITLE
誤植：「3.1.3. 数値を見ながら計算の流れを確認」

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [japan-medical-ai/medical-ai-course-materials#86]
[該当項](https://japan-medical-ai.github.io/medical-ai-course-materials/notebooks/Introduction_to_Neural_Network.html#%E6%95%B0%E5%80%A4%E3%82%92%E8%A6%8B%E3%81%AA%E3%81%8C%E3%82%89%E8%A8%88%E7%AE%97%E3%81%AE%E6%B5%81%E3%82%8C%E3%82%92%E7%A2%BA%E8%AA%8D)にある些細な計算間違いが気になりました。

<img src="https://latex.codecogs.com/gif.latex?u_{12}&=-2\times&space;2-3\times&space;3-1\times&space;1=-11&space;\\&space;\rightarrow&space;u_{12}&=-2\times&space;2-3\times&space;3-1\times&space;1=-14" />

<img src="https://latex.codecogs.com/gif.latex?h_{12}&space;&=&space;\max(0,&space;-11)&space;=&space;0&space;\\&space;\rightarrow&space;h_{12}&space;&=&space;\max(0,&space;-14)&space;=&space;0" />

**Comment by suga93** [comment]
該当箇所について，修正・反映致しました．
ご指摘いただきありがとうございました．
