### ISSUE TITLE
7.3. データセット `data.h5` → `seq.h5`

### ISSUE THREAD

**Issue by shu65** [japan-medical-ai/medical-ai-course-materials#91]
7.3. データセットの部分で`wget`で落としてきているファイル名は`seq.h5`なのに対して、本文中では`data.h5`になっている。

**Comment by suga93** [comment]
以下のPRで対応しました．ご指摘ありがとうございました．
https://github.com/japan-medical-ai/medical-ai-course-materials/pull/92
